name: app_state_examples
description: Examples for app_state Flutter package, a bloc-based state management solution on top of Router API for larger apps.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  app_state: ^0.6.10
  flutter: { sdk: flutter }
  keyed_collection_widgets: ^0.3.2
  url_launcher: ^6.1.5

#dependency_overrides:
#  app_state:
#    path: ../flutter-app-state

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test: { sdk: flutter }

flutter:
  uses-material-design: true
