name: app_state_5_route_result
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  app_state: ^0.5.0
  keyed_collection_widgets: ^0.3.2

#dependency_overrides:
#  app_state:
#    path: ../../flutter-app-state

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
